name: tenpy
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - cython>=0.29
  - mkl
  - mkl-devel
  - libblas=*=*mkl  # pin BLAS to use MKL
  - bottleneck
  - pip
  - setuptools>=68.0.0
  - h5py
  - pyyaml
  - pytest>=6.0
  - ruff
  - pre-commit
  - flake8
  - flake8-rst-docstrings
