name: tenpydoc
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy>=1.13
  - scipy>=0.18
  - cython>=0.29
  - bottleneck
  - pip
  - setuptools>=30.3.0
  - h5py
  - pyyaml
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - matplotlib
  - ipykernel
  - nbsphinx
  - graphviz
  - pandoc
  - sphinx-copybutton
