name: Upload Python Package to PyPI

on:
  # when a release is created
  release:
    types: [created]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'  # use minimum version that we support
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel build
    - name: Build
      run: python -m build .
    - name: Install for test
      run: python -m pip install .
    - name: quicktest
      run: |
        python -m pip install pytest
        pytest -m "not slow"
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_password }}
